# fly.toml app configuration file generated for seclook on 2024-01-02T00:00:00-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "seclook"
primary_region = "den"

[http_service]
  internal_port = 8080
  force_https = false
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]